### PR TITLE
Fix moist gpu example failure for mixed spaces expression

### LINKED ISSUE #2191: Mismatched spaces error in vertical_diffusion_boundary_layer_tendency!
Current failure in the moist model
https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/88#018af76a-8b21-411b-a348-5aa181011b5f/138-220

which is here:
https://github.com/CliMA/ClimaAtmos.jl/blob/641cdeb37295822760fc74f9671ff73f06950bee/src/prognostic_equations/vertical_diffusion_boundary_layer.jl#L92-L98

From what I can tell, the problem is that we have fields at two different levels (one at level 1, one at level half).

For now, I think the easiest option might be to simply get rid of the error. Hopefully we can address this properly as part of https://github.com/CliMA/ClimaCore.jl/issues/1120

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR fixes the next breaking piece, blocking us from #1980. Closes #2191.

### CODE REVIEW

File: src/prognostic_equations/vertical_diffusion_boundary_layer.jl [hunk 1]
```diff
@@ -85,15 +85,14 @@ function vertical_diffusion_boundary_layer_tendency!(
     FT = eltype(Y)
     interior_uₕ = Fields.level(Y.c.uₕ, 1)
     interior_coordinates = Fields.level(Fields.coordinate_field(Y.c), 1)
```
Comment (szy21) [inline src/prognostic_equations/vertical_diffusion_boundary_layer.jl:87]:
```suggestion
```

**Review by szy21 — APPROVED** [review]

File: src/prognostic_equations/vertical_diffusion_boundary_layer.jl (hunk 1 above)
Comment (charleskawczynski) [reply src/prognostic_equations/vertical_diffusion_boundary_layer.jl:87]: Ah, this is still used to get `ᶜΔz_surface`, but I'll grab it from `interior_uₕ` instead.

Comment (szy21) [reply src/prognostic_equations/vertical_diffusion_boundary_layer.jl]: Ah ok, thanks! I was on my phone and didn’t see the whole file 😂

Comment (szy21) [reply src/prognostic_equations/vertical_diffusion_boundary_layer.jl]: Actually, does Δz_field for a center field give the interval between cell center or cell face?

Comment (charleskawczynski) [reply src/prognostic_equations/vertical_diffusion_boundary_layer.jl]: > Actually, does Δz_field for a center field give the interval between cell center or cell face?

I had thought about this, I think it would only make sense that it is the distance between cell faces, because the data lives on cell centers (and it should be centered / symmetric about cell centers). I should verify that, though. It returns `lg.∂x∂ξ.components.data.:9` for us, @simonbyrne, can you confirm that this is correct?

The MSE tables didn't need updated, so, if we have regression tests that use this, we should be in the clear.

Comment (szy21) [reply src/prognostic_equations/vertical_diffusion_boundary_layer.jl]: We do have regression test for this, this should be correct then.
