### PR TITLE
use parameters for surface albedo

### LINKED ISSUE #2757: Add refractive index to parameters
The refractive index (n) in the regression-based albedo can be calibrated to match observations. It would be good to make it a parameter.

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Use clima parameters for ocean surface albedo and water refractive index. Closes #2757 

## To-do

- [x] update ClimaParams in all environments

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

File: src/parameters/Parameters.jl [hunk 1]
```diff
@@ -74,6 +74,9 @@ Base.@kwdef struct ClimaAtmosParameters{FT, TP, RP, IP, MPP, WP, SFP, TCP} <:
     zd_viscous::FT
     zd_rayleigh::FT
     kappa_2_sponge::FT
+    # Radiation
+    ocean_surface_albedo::FT
```
Comment (LenkaNovak) [inline src/parameters/Parameters.jl:78]: It could be more clear to call this "idealized_ocean_albedo".

**Review by LenkaNovak — APPROVED** [review]
LGTM, thank you, just a minor comment on the naming.

File: src/parameters/Parameters.jl (hunk 1 above)
Comment (szy21) [reply src/parameters/Parameters.jl:78]: Sounds good, I will add this to the next ClimaParams breaking release.

File: src/parameters/create_parameters.jl [hunk 2]
```diff
@@ -111,6 +111,8 @@ function create_parameter_set(config::AtmosConfig)
         :drag_layer_vertical_extent => :σ_b,
         :kappa_2_sponge => :kappa_2_sponge,
         :held_suarez_minimum_temperature => :T_min_hs,
+        :ocean_surface_albedo => :ocean_surface_albedo,
```
Comment (nefrathenrici) [inline src/parameters/create_parameters.jl:114]:
```suggestion
        :ocean_surface_albedo => :idealized_ocean_albedo,
```
Given @LenkaNovak's comment, we can rename this within ClimaAtmos without a new release.

Comment (szy21) [reply src/parameters/create_parameters.jl:114]: Thanks! I will change this.
