### PR TITLE
fix cached boundary values in env

### LINKED ISSUE #3971: Fix calculation of environment u_3 in prognostic EDMF
Currently, u_3 at the boundary violates domain decomposition, and we recompute it when calculating the mass flux [here](https://github.com/CliMA/ClimaAtmos.jl/blob/f496d5ca327e7bb20fbb1b8d95e3143d9b13062c/src/prognostic_equations/edmfx_sgs_flux.jl#L55). We should move this to precomputed quantities.

### LINKED ISSUE #3981: Recomputing u_3 in sgs mass flux is problematic when environment area fraction is 0
I just realized [this](https://github.com/CliMA/ClimaAtmos.jl/blob/789a215e53f1157b1ba801a23735a0ee91e0450d/src/prognostic_equations/edmfx_sgs_flux.jl#L57) will cause an issue if the environment area fraction is close to 0 (which could happen in global runs). @sajjadazimi Could you modify it following e.g. [here](https://github.com/CliMA/ClimaAtmos.jl/blob/789a215e53f1157b1ba801a23735a0ee91e0450d/src/utils/variable_manipulations.jl#L488)?

### PR DESCRIPTION
**Pull request by sajjadazimi**
## Purpose 
Fix cached boundary values in env by changing the order of functions calls in set_cache
Closes #3971 Closes #3981 

----
- I have read and checked the items on the review checklist.

### CODE REVIEW

File: src/cache/precomputed_quantities.jl [hunk 1]
```diff
@@ -502,6 +512,19 @@ NVTX.@annotate function set_explicit_precomputed_quantities!(Y, p, t)
 
     if turbconv_model isa PrognosticEDMFX
         set_prognostic_edmf_precomputed_quantities_bottom_bc!(Y, p, t)
+    elseif turbconv_model isa DiagnosticEDMFX
+        set_diagnostic_edmf_precomputed_quantities_bottom_bc!(Y, p, t)
```
Comment (szy21) [inline src/cache/precomputed_quantities.jl:529]: The `bottom_bc` should be after `draft` (otherwise it is overwritten by the `draft` function). I think the easiest way to make this work is to move `bottom_bc` to implicit tendency, but after `draft`.

Comment (szy21) [reply src/cache/precomputed_quantities.jl:529]: resolved offline: this works too.

**Review by szy21 — APPROVED** [review]
Thank you!
